- name: Install and configure KDE with i3wm
  hosts: localhost
  gather_facts: yes
  become: no
  vars:
    picom_github_repo: https://github.com/yshui/picom.git
    local_repo_dir: "{{ ansible_env.HOME }}/src"
    picom_src_dir: "{{ ansible_env.HOME }}/src/picom"
  tasks:
    - name: Install dependencies
      package:
        name:
          - asciidoc
          - gcc
          - libconfig-dev
          - libdbus-1-dev
          - libev-dev
          - libevdev-dev
          - libgl1-mesa-dev
          - libpcre2-dev
          - libpixman-1-dev
          - libx11-xcb-dev
          - libxcb1-dev
          - libxcb-composite0-dev
          - libxcb-damage0-dev
          - libxcb-glx0-dev
          - libxcb-image0-dev
          - libxcb-present-dev
          - libxcb-randr0-dev
          - libxcb-render0-dev
          - libxcb-render-util0-dev
          - libxcb-shape0-dev
          - libxcb-xfixes0-dev
          - libxcb-xinerama0-dev
          - libxext-dev
          - meson
          - uthash-dev
          - build-essential
          - libpcre++-dev
        state: present
      become: yes
    - name: Ensure directories exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: 0750
      loop:
        - "{{ src_dir }}"
    - name: Download and unpack picom source
      ansible.builtin.unarchive:
        src: "{{ picom_src_url }}"
        dest: "{{ src_dir }}"
        remote_src: yes
