- name: Configure KDE Konsole
  hosts: localhost
  gather_facts: yes
  become: no
  vars:
    config_dir: "{{ ansible_env.HOME }}/.config"
    profiles_dir: "{{ ansible_env.HOME }}/.local/share/konsole"
    soloraized: "{{ ansible_env.HOME }}/.local/share/konsole/Soloraized.profile"
    konsolerc: "{{ ansible_env.HOME }}/.config/konsolerc"
  tasks:
    - name: Install required packages
      package:
        name:
          - konsole
        state: present
      become: yes
    - name: Ensure directories exists
      file:
        path: "{{ item }}"
        state: directory
        mode: 0750
      loop:
        - "{{ config_dir }}"
    - name: Ensure config files in place
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: present
      loop:
        - { src: konsolerc, dest: "{{ konsolerc }}" }
        - { src: Soloraized.profile, dest: "{{ soloraized }}" }
