---
- name: Install and configure ssh server
  hosts: localhost
  become: yes
  gather_facts: yes
  tasks:
    - name: Install packages
      package:
        name:
          - openssh-client
          - openssh-server
        state: present
