- name: Config Vim with plugins
  hosts: localhost
  gather_facts: yes
  become: no
  vars:
    vim_dir: "{{ ansible_env.HOME }}/.vim"
    vimrc: "{{ ansible_env.HOME }}/.vimrc"
  tasks:
    - name: Install required packages
      package:
        name:
          - git
          - silversearcher-ag
        state: present
      become: yes
    - name: Ensure .vim/{autoload,bundle} directory exists
      file:
        path: "{{ item }}"
        state: directory
        mode: 0750
      loop:
        - "{{ vim_dir }}"
        - "{{ vim_dir }}/autoload"
        - "{{ vim_dir }}/bundle"
        - "{{ vim_dir }}/colors"
    - name: install the Hack font
      ansible.builtin.unarchive:
        src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Hack.zip
        dest: /usr/share/fonts/
        list_files: true 
        remote_src: yes
      become: yes
    - name: Ensure Pathogen is in place
      get_url:
        dest: "{{ vim_dir }}/autoload/pathogen.vim"
        url: https://tpo.pe/pathogen.vim
    - name: Deploy plugins
      git:
        dest: "{{ vim_dir }}/bundle/{{ item.name }}"
        repo: "{{ item.url }}"
        clone: yes
        update: yes
        recursive: no
      loop:
      - name: vim-airline
        url: https://github.com/vim-airline/vim-airline
      - name: vim-airline-themes
        url: https://github.com/vim-airline/vim-airline-themes
      - name: vim-devicons
        url: https://github.com/ryanoasis/vim-devicons.git
      - name: vim-floaterm
        url: https://github.com/voldikss/vim-floaterm
      - name: nerdtree
        url: https://github.com/preservim/nerdtree
      - name: nerdtree-git-plugin
        url: https://github.com/Xuyuanp/nerdtree-git-plugin.git
      - name: solarized
        url: git://github.com/altercation/vim-colors-solarized.git
    - name: Ensure .vimrc config in place
      copy:
        src: vimrc
        dest: "{{ vimrc }}"
        backup: yes
        mode: 0640
