- name: Install required packages
  package:
    name:
      alacritty, dmenu, sway, xrandr
    state: present
  become: yes
- name: Ensure directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
  loop:
    - "{{ sway_dir }}"
- name: Ensure config files are in place
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    backup: yes
  loop:
    - { src: sway/config, dest: "{{ sway_dir }}" }
- name: Ensure scripts are in place
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    backup: yes
    mode: 0700
  loop:
    - { src: sway/scripts, dest: "{{ sway_dir }}" }
- name: Clone i3blocks-contrib
  git:
    dest: "{{ sway_dir }}/{{ item.name }}"
    repo: "{{ item.url }}"
    clone: yes
    update: yes
    recursive: no
  loop:
  - name: i3blocks-contrib
    url: https:/github.com/vivien/i3blocks-contrib
