- name: Install required packages
  package:
    name:
      waybar
    state: present
  become: yes
- name: Ensure directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
  loop:
    - "{{ waybar_dir }}"
- name: Ensure config files are in place
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    backup: yes
  loop:
    - { src: waybar/config, dest: "{{ waybar_dir }}" }
