- name: Install brave browser
  hosts: localhost
  gather_facts: yes
  become: yes
  vars:
     sources_file: "/etc/apt/sources.list.d/brave-browser-release.list"
  tasks:
    - name: Install prerequisites
      package:
        name:
          - apt-transport-https
          - curl
          - gnupg
        state: present
    - name: Add brave apt key
      ansible.builtin.apt_key:
        url: https://brave-browser-apt-release.s3.brave.com/brave-core.asc
        keyring: /etc/apt/trusted.gpg.d/brave-browser-release.gpg
        state: present
    - name: Add the sources file
      copy:
        src: brave-browser-release.list
        dest: "{{ sources_file }}"
    - name: Installing Brave
      package:
        name:
          - brave-browser
        update_cache: yes
