- name: Install docker deps
  package:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present

- name: Add pgp key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Save the current Ubuntu release version into a variable
  shell: lsb_release -cs
  register: ubuntu_version

- name: Add Docker Repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_version.stdout }} stable"
    state: present

- name: Update apt
  ansible.builtin.apt:
    update_cache: yes
    force_apt_get: yes

- name: Install docker
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    
- name: Enable docker service
  systemd:
    state: started
    name: docker
    enabled: yes
    
- name: Add docker group
  group:
    name: docker
    state: present
      
- name: Add user to docker group
  user:
    name: '{{ username }}'
    append: yes
    groups: 
      - docker
    state: present

- name: Save the kernel name into a variable
  shell: uname -s
  register: kernel_name

- name: Save the architecture into a variable
  shell: uname -m
  register: arch

- name: Download docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ kernel_name.stdout }}-{{ arch.stdout }}"
    dest: /usr/local/bin/docker-compose
    mode: 0755
