- name: Install and configure vim
  tags: vim
  import_tasks: vim.yaml
- name: Install chruby and ruby-install
  tags: ruby
  import_tasks: ruby.yaml
- name: Install and configure git
  tags: git
  import_tasks: git.yaml
- name: Install qmk
  tags: qmk, keybaord
  import_tasks: qmk.yaml