- name: Install and configure vim
  tags: vim
  import_tasks: vim.yaml
- name: Install chruby and ruby-install
  tags: ruby
  import_tasks: ruby.yaml
- name: Install and configure git
  tags: git
  import_tasks: git.yaml
    #- name: Install qmk
    #  tags: qmk, keybaord
    #  import_tasks: qmk.yaml
- name: Install docker
  tags: docker
  become: yes
  import_tasks: docker.yaml
- name: SSH
  tags: ssh
  import_tasks: ssh.yaml
- name: mkcert
  tags: mkcert
  import_tasks: mkcert.yaml
