- name: Install ssh client and server
  package:
    name: openssh, openssh-server
    state: present
  become: yes

- name: Enable ssh service
  systemd:
    state: started
    name: sshd
    enabled: yes
  become: yes

- name: Copy authorized keys from github
  get_url:
    mode: '0600'
    backup: yes
    dest: "{{ home }}/.ssh/authorized_keys"
    url: https://github.com/mcmillanator.keys
