- name: Install required packages
  package:
    name:
      - git
      # grip is a github markdown server useful for markdown previews in the browser
      - grip
      - silversearcher-ag
      - neovim
    state: present
  become: yes
- name: Ensure directories exists for fonts
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - "/usr/share/fonts"
  become: yes
- name: Ensure directories exists
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
  loop:
    - "{{ vim_dir }}"
    - "{{ vim_dir }}/autoload"
    - "{{ vim_dir }}/bundle"
    - "{{ vim_dir }}/colors"
    - "{{ vim_dir }}/undo-history"
- name: install the Hack font
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Hack.zip
    dest: /usr/share/fonts/
    list_files: true 
    remote_src: yes
    creates: "/usr/share/fonts/Hack Regular Nerd Font Complete.ttf"
  become: yes
- name: Ensure Pathogen is in place
  get_url:
    dest: "{{ vim_dir }}/autoload/pathogen.vim"
    url: https://tpo.pe/pathogen.vim
- name: Deploy plugins
  git:
    dest: "{{ vim_dir }}/bundle/{{ item.name }}"
    repo: "{{ item.url }}"
    clone: yes
    update: yes
    recursive: no
  loop:
  - name: airline
    url: https://github.com/vim-airline/vim-airline.git
  - name: airline-themes
    url: https://github.com/vim-airline/vim-airline-themes.git
  - name: ALE
    url: https://github.com/dense-analysis/ale.git
  - name: ctrlp
    url: https://github.com/ctrlpvim/ctrlp.vim.git
  - name: devicons
    url: https://github.com/ryanoasis/vim-devicons.git
  - name: dispatch
    url: https://github.com/tpope/vim-dispatch.git
  - name: floaterm
    url: https://github.com/voldikss/vim-floaterm.git
  - name: nerdtree
    url: https://github.com/preservim/nerdtree.git
  - name: nerdtree-git-plugin
    url: https://github.com/Xuyuanp/nerdtree-git-plugin.git
  - name: solarized
    url: https://github.com/altercation/vim-colors-solarized.git
  - name: uninpaired
    url: https://tpope.io/vim/unimpaired.git
  - name: vim-easymotion
    url: https://github.com/asvetliakov/vim-easymotion.git
  - name: vim-fugitive
    url: https://github.com/tpope/vim-fugitive.git
  - name: vim-ruby
    url: https://github.com/vim-ruby/vim-ruby.git
  - name: vim-test
    url: https://github.com/janko-m/vim-test.git
  - name: vim-signify
    url: https://github.com/mhinz/vim-signify.git
  - name: vim-rails
    url: https://github.com/tpope/vim-rails.git
  - name: vim-bundler
    url: https://github.com/tpope/vim-bundler.git
  - name: vim-endwise
    url: https://github.com/tpope/vim-endwise.git
  - name: vim-startify
    url: https://github.com/mhinz/vim-startify.git
  - name: vim-obsession
    url: https://github.com/tpope/vim-obsession.git
  - name: nvim-lspconfig
    url: https://github.com/neovim/nvim-lspconfig.git

- name: Ensure .vimrc config in place
  copy:
    src: vimrc
    dest: "{{ vimrc }}"
    backup: yes
    mode: 0640
- name: Ensure .nvim config in place
  copy:
    src: nvim
    dest: "{{ nvim_config }}"
    backup: yes
    mode: 0640
