" Pathogen for installing plugins
execute pathogen#infect()
" turn on mouse for all vim modes
set mouse=a
" syntax highlighting on
syntax on
filetype plugin indent on
" solarized color them
colorscheme solarized
" solarized dark
set background=dark
" number of spaces that a <Tab> counts for
set tabstop=2
set shiftwidth=2
" use spaces to insert a <Tab>
set expandtab
" line numbers
set number
" relative line numbers
set relativenumber
" highlight search
set hls
" use system clipboard
set clipboard=unnamedplus
" enable spell check
set spell spelllang=en_us
" vim-obsession options
set sessionoptions="blank,buffers,curdir,folds,help,tabpages,winsize,terminal"
" turn on paste mode
set paste
" keep buffers hidden in the background, useful for keeping unsaved changes in multiple buffers
set hidden
" use an undo file
set undofile
" set a directory to store the undo history
set undodir=~/.vim/undo-history/

" Open man page in a window
" pressing K will open the man page of the highlighted word
runtime! ftplugin/man.vim

" Configuration vim Airline
let g:airline_theme='solarized'
let g:airlie_solarized_bg='dark'
let g:airline#extensions#tabline#enabled=1
let g:airline_powerline_fonts=1
set laststatus=2

" Silver Searcher
if executable('ag') 
    " Note we extract the column as well as the file and line number
    set grepprg=ag\ --nogroup\ --nocolor\ --column
    set grepformat=%f:%l:%c%m

    " Use ag in CtrlP for listing files. Lightning fast and respects
    " .gitignore
    let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'

    " ag is fast enough that CtrlP doesn't need to cache
    let g:ctrlp_use_caching = 0
endif
" bind K to grep word under cursor
nnoremap K :grep! "\b<C-R><C-W>\b"<CR>:cw<CR>

" Configuration NERDTree
nnoremap <C-n> :NERDTreeToggle<CR>
nnoremap <C-f> :NERDTreeFind<CR>
let NERDTreeShowLineNumbers=1

" Configuration floaterm
let g:floaterm_keymap_toggle = '<F12>'

" splits
set splitbelow
set splitright
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" ctrlp
set runtimepath^=~/.vim/bundle/ctrlp.vim

" ALE
nmap <silent> [W <Plug>(ale_first)
nmap <silent> [w <Plug>(ale_previous)
nmap <silent> ]W <Plug>(ale_last)
nmap <silent> ]w <Plug>(ale_next)

" vim-test
let test#strategy = 'dispatch'
nmap <silent> t<C-n> :TestNearest<CR>
nmap <silent> t<C-f> :TestFile<CR>
nmap <silent> t<C-s> :TestSuite<CR>
nmap <silent> t<C-l> :TestLast<CR>
nmap <silent> t<C-g> :TestVisit<CR>

