vim_dir: "{{ ansible_env.HOME }}/.vim"
vimrc: "{{ ansible_env.HOME }}/.vimrc"
# src_dir is used for downloading source files to compile code
src_dir: "{{ ansible_env.HOME }}/.src"
mkcert_dir: "{{ ansible_env.HOME }}/.src/mkcert"
home: "{{ ansible_env.HOME }}"
omz_dir: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/"
username: "{{ ansible_env.USER }}"
