---
- name: Set up host for Docker with GPU support
  hosts: localhost
  become: yes
  tasks:
    - name: Update package lists and install prerequisites
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Add Docker repository and GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ ansible_architecture }} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Update package lists and install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: yes

    - name: Enable Docker to start on boot
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Install NVIDIA CUDA Toolkit and cuDNN (runtime and developer libraries)
      ansible.builtin.get_url:
        url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004.pin
        dest: /etc/apt/preferences.d/cuda-repository-pin-600
        mode: '0644'
      ansible.builtin.apt_key:
        url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/7fa2af80.pub
        state: present
      ansible.builtin.apt_repository:
        repo: "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64 /"
        state: present
      apt:
        name:
          - cuda-11-4
          - libcudnn8
          - libcudnn8-dev
        state: present
        update_cache: yes

    - name: Install the NVIDIA Container Toolkit
      ansible.builtin.apt_key:
        url: https://nvidia.github.io/nvidia-docker/gpgkey
        state: present
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/nvidia-container-archive-keyring.gpg] https://nvidia.github.io/nvidia-docker/{{ ansible_distribution | lower }}{{ ansible_distribution_major_version }}/ nvidia-docker main"
        state: present
      apt:
        name:
          - nvidia-docker2
        state: present
        update_cache: yes

    - name: Restart the Docker daemon to apply the changes
      systemd:
        name: docker
        state: restarted
...

