" Pathogen for installing plugins
execute pathogen#infect()
" syntax highlighting on
syntax on
filetype plugin indent on
" solarized color them
colorscheme solarized
" solarized dark
set background=dark
" number of spaces that a <Tab> counts for
set tabstop=2
set shiftwidth=2
" use spaces to insert a <Tab>
set expandtab
" line numbers
set number
" relative line numbers
set relativenumber
" highlight search
set hls
" use system clipboard
set clipboard=unnamedplus
" enable spell check
set spell spelllang=en_us
" vim-obsession options
set sessionoptions="blank,buffers,curdir,folds,help,tabpages,winsize,terminal"

" Open man page in a window
" pressing K will open the man page of the highlighted word
runtime! ftplugin/man.vim

" Configuration vim Airline
let g:airline_theme='solarized'
let g:airlie_solarized_bg='dark'
let g:airline#extensions#tabline#enabled=1
let g:airline_powerline_fonts=1
set laststatus=2

" Silver Searcher
if executable('ag') 
    " Note we extract the column as well as the file and line number
    set grepprg=ag\ --nogroup\ --nocolor\ --column
    set grepformat=%f:%l:%c%m
endif
nmap <silent> <RIGHT> :cnext<CR>
nmap <silent> <LEFT> :cprev<CR>

" Configuration NERDTree
nnoremap <C-n> :NERDTreeToggle<CR>
nnoremap <C-f> :NERDTreeFind<CR>

" Configuration floaterm
let g:floaterm_keymap_toggle = '<F12>'

" splits
set splitbelow
set splitright
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>
