---
- name: Install and configure the host machine for vms with passthrough
  hosts: localhost
  gather_facts: yes
  become: yes
  vars:
    user: "{{ ansible_env.USER }}"
  tasks:
    - name: Install deps
      package:
        name:
          - qemu-kvm
          - qemu-utils
          - libvirt-daemon-system
          - libvirt-clients
          - virt-manager
          - ovmf
    - name: Download virtio driver iso
      get_url:
        url: https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/stable-virtio/virtio-win.iso
        dest: /mnt/isos/virtio-win.iso
        checksum: sha256:af2b3cc9fa7905dea5e58d31508d75bba717c2b0d5553962658a47aebc9cc386
        mode: 0755
    - name: Append groups to user
      user:
        name: "{{ user }}"
        groups: kvm,libvirt
        append: yes
    - name: Ensure grub loads iommu
      copy:
        src: grub
        dest: /etc/default/grub
        backup: yes
        owner: root
        group: root
        mode: 0644
    - name: Update grub
      command: update-grub
