- name: Update grub
  command: grubby --grub2
  become: yes
- name: Update dracut
  command: dracut -f
  become: yes
  notify: Update drivers
- name: Update drivers
  command: driverctl -v set-override 0000:03:00.2 vfio-pci
  become: yes

