- name: Install Inter-VM shared memory kernel module
  become: no
  hosts: localhost
  gather_facts: yes
  vars:
    build_dir: "{{ src_dir }}/module"
    src_dir: "{{ ansible_env.HOME }}/src/looking-glass"
  tasks:
    - name: Ensure directories exist
      file:
        path: "{{ item }}"
        state: directory
        mode: 0750
      loop:
        - "{{ build_dir }}"
    - name: make the IVSHMEM kernel module
      command: make "{{ build_dir }}"
      args:
        chdir: "{{ build_dir }}"
        creates: "{{ build_dir }}/kvmfr.mod"
    - name: install module prerequ uio
      become: yes
      command: modprobe uio
      args:
        chdir: "{{ build_dir }}"
        creates: /dev/uio0
    - name: install module kvmfr
      become: yes
      command: insmod kvmfr.ko
      args:
        chdir: "{{ build_dir }}"
        creates: /dev/uio0
    - name: Set permissions
      become: yes
      file:
        path: "{{ item }}"
        owner: "{{ ansible_env.USER }}"
      loop:
        - /dev/uio0
