- name: Install and configure i3wm
  hosts: localhost
  gather_facts: yes
  become: no
  vars:
    i3_dir: "{{ ansible_env.HOME }}/.i3"
  tasks:
    - name: Install required packages
      package:
        name:
          - dmenu
          - i3blocks
          - i3status
          - i3-wm
          - playerctl
        state: present
      become: yes
    - name: Ensure directories exist
      file:
        path: "{{ item }}"
        state: directory
        mode: 0750
      loop:
        - "{{ i3_dir }}"
    - name: Ensure config files in place
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        backup: yes
      loop:
        - { src: .i3, dest: "{{ ansible_env.HOME }}" }
    - name: Clone i3blocks-contrib
      git:
        dest: "{{ i3_dir }}/{{ item.name }}"
        repo: "{{ item.url }}"
        clone: yes
        update: yes
        recursive: no
      loop:
      - name: i3blocks-contrib
        url: https://github.com/vivien/i3blocks-contrib
